version: "2"

services:
    db:
        image: 'mongo:latest'
        volumes: 
            - db:/data/db
    cms:
        networks:
            - default
            - backend
        build: .
        volumes: 
            - ./src/addons:/var/www/html/addons
            - ./src/config:/var/www/html/config
            - storage:/var/www/html/storage
        environment:
            VIRTUAL_HOST: ${DOMAIN}
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: ${DOMAIN}
            LETSENCRYPT_EMAIL: mirko.friedrich@blandland.de
            COCKPIT_SESSION_NAME: cockpit
            COCKPIT_SALT: ASLKDÖAS61389KDASKDÖLASDH_HAJKDS1254
            COCKPIT_DATABASE_SERVER: 'mongodb://db:27017'
            COCKPIT_DATABASE_NAME: cms
        depends_on:
            - db
        ports:
            - 8080:80
volumes:
    db:
    storage:

networks:
    backend:
    default:
        external:
            name: web
