version: "2"

services:
    db:
        image: 'mongo:latest'
        volumes: 
            - ./data/db:/data/db
    cms:
        networks:
            - default
            - backend
        build: .
        environment:
            VIRTUAL_HOST: ${DOMAIN}
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: ${DOMAIN}
            LETSENCRYPT_EMAIL: mirko.friedrich@blandland.de
            COCKPIT_SESSION_NAME: cockpit
            COCKPIT_SALT: ASLKDÖAS61389KDASKDÖLASDH_HAJKDS1254
            COCKPIT_DATABASE_SERVER: 'mongodb://db:27017'
            COCKPIT_DATABASE_NAME: cms
        depends_on:
            - db
        ports:
            - 80

networks:
    backend:
    default:
        external:
            name: web
